name: "CI: Brainbox"

on:
  push:
    branches: [main]
    paths: ["brainbox/**", "docker/brainbox/**"]
  pull_request:
    paths: ["brainbox/**", "docker/brainbox/**"]

defaults:
  run:
    working-directory: brainbox

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: astral-sh/setup-uv@v4

      - run: uv sync --group dev

      - run: uv run python -m pytest

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: astral-sh/setup-uv@v4

      - run: uv sync --group dev

      - run: uv run ruff check src/

      - run: uv run ruff format --check src/
